server:
  port: 80  #设置服务器端口号

#HikariCP数据源设置
#spring.datasource.driver-class-name = com.mysql.jdbc.Driver;
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?characterEncoding=utf-8
    username: root
    password: "0418"

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect